<?php


/**
 * Implements hook_menu().
 */
function diginole_feas_webservice_menu() {
  $items = array();

  $items['diginole/webservices/feas/query'] = array (
    'page callback' => 'diginole_feas_webservice_query_responder',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Callback functions
 */
function diginole_feas_webservice_query_responder() {
  module_load_include('inc', 'diginole_feas_webservice', 'includes/responders');
  $response = diginole_feas_webservice_query_processor($_GET);
  Header('Content-type: text/xml');
  echo $response;
  drupal_exit();
}
